pull_request_rules:
  - name: Merge dev to main after CI passes
    conditions:
      - "base=main"
      - "head=dev"
      - "status-success=Jenkins"
    actions:
      merge:
        method: squash
