name: Auto Merge Dev → Main

on:
  workflow_run:
    workflows: ["Jenkins CI"]  # Change to your Jenkins workflow name
    types:
      - completed  # Runs when Jenkins job finishes

permissions:
  contents: write  # Allow pushing changes

jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Run only if Jenkins job succeeds

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Fetch full commit history

      - name: Pull latest dev changes
        run: |
          git fetch origin dev  # Ensure we have the latest dev branch
          git merge origin/dev --no-edit  # Merge dev into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
